### ISSUE TITLE
separation assertion in run_workflow as a separate method 

### ISSUE THREAD

**Issue by xquek** [EliLillyCo/pytest-wdl#13]
Hi there, 

I was wondering if it will be considered an enhancement/useful to refactor the assertion from the `run_workflow` as a separate method. 

see branch [feature/custome_assertion](https://github.com/EliLillyCo/LRL_cromwell_test_runner/tree/feature/custom_assertion) 

The main motivation will be to increase the extensibility of `CromwellHarness` allow us to use set our own assertion either via monkey patching or class inheritance.

At the same time, this will reduce the size of the `run_workflow` method also allow testing of assertion vs run_workflow separately

Currently, we have to do it via the `Data` object for the custom assertion as well. 

If this is desired, I can start adding unit test for this feature.

**Comment by jdidion** [comment]
This has been done
