### ISSUE TITLE
installing all extras fails

### ISSUE THREAD

**Issue by michaeltneylon** [EliLillyCo/pytest-wdl#143]
`pip install pytest-wdl[all]` fails with:

> dxpy 0.298.1 requires requests<2.24.0,>=2.8.0, but you'll have requests 2.24.0 which is incompatible.

`dxpy` recently released 0.298.1 which includes a change restricting the version of `requests`:
https://github.com/dnanexus/dx-toolkit/commit/dd2ea2d14b41a74fa46ff2c7474577839a44b1ce#diff-0efe7843416024cae44cfaaff0d0f35dR7

This causes the installation to fail since `http` extra install `requests` without version restriction, and other dependencies may require `requests`, which causes a conflict in dependencies and makes the installation skip `dxpy` extra.

This will only be an issue for a short period of time because `pip` will resolve dependencies in a more strict fashion starting in October. That is proved as working by using the new feature now and installing with:

`pip install --use-feature=2020-resolver pytest-wdl[all]`

or explicitly set requests version to workaround:

`pip install requests==2.23.0 pytest-wdl[all]`

---
relating to #139 since we have not yet released a version restriction on `pytest`, a full solution to install pytest-wdl with all extras today is now:

`pip install requests==2.23.0 pytest==5.3.5 pytest-wdl[all]` 
or 
`pip install --use-feature=2020-resolver pytest==5.3.5 pytest-wdl[all]`

**Comment by jdidion** [comment]
This is resolved by restricting the version of requests in setup.py `http` extra
