### ISSUE TITLE
Put headers config in test_data.json file

### ISSUE THREAD

**Issue by jdidion** [EliLillyCo/pytest-wdl#29]
It doesn't make sense to specify a single set of http headers to use, as data files may come from different sources. Git rid of the http_header_map and http_headers fixtures, and instead add a section of test_data.json that maps a URI pattern to a header name and environment variable from which to obtain the value. Header name/envvar pairs can also be specified within each data file descriptor.

**Comment by michaeltneylon** [comment]
closed by #33
