### ISSUE TITLE
Have you looked into pytest-workflow?

### ISSUE THREAD

**Issue by rhpvorderman** [EliLillyCo/pytest-wdl#84]
Dear maintainers,

A test framework for WDL! It is great that you pick up this task.

I have been working on a similar test framework for all workflow systems called [pytest-workflow](https://github.com/lumc/pytest-workflow). Together with my colleagues at LUMC we came up with a [simple yaml test format](https://pytest-workflow.readthedocs.io/en/stable/#test-options) to test workflows.

It is [fully documented](https://pytest-workflow.readthedocs.io) and it includes [specific examples for use with cromwell](https://pytest-workflow.readthedocs.io/en/stable/#wdl-with-cromwell-example). We test all pipelines in [BioWDL](https://github.com/biowdl) with pytest-workflow. 

Since pytest-workflow is workflow agnostic, it has no code to interact specifically with cromwell. This has the advantage that the interface is straightforward. Inputs are provided by providing a cromwell inputs json. Cromwell is run by issuing a cromwell command. Testing whether files are present is very easy. File contents can be checked with little effort etc. It also allows for custom advanced python tests.

It is great to find another group of people who is enthusiastic about testing WDL! Maybe we can help each other out and prevent duplication of effort. 

Best regards,
Ruben Vorderman

**Comment by jdidion** [comment]
Looks cool - nice work!
