### ISSUE TITLE
test_data.json in same folder as test file fails when not in folder called `tests`

### ISSUE THREAD

**Issue by jtratner** [EliLillyCo/pytest-wdl#86]
This folder structure will fail with an inability to find test_data.json

```
/
test_workflow.py
test_data.json
$ pytest test_workflow.py
```

Because it'll attempt to look in the `tests` folder first.  It'd be nice if it started relative to the actual test file (or update the docs to note that it always looks in test_folder).

**Comment by jdidion** [comment]
Good suggestion - will get this into the 1.2.0 release

**Comment by jdidion** [comment]
1.2.0 is now released. This should be fixed.
