### ISSUE TITLE
miniwdl executor: Non-friendly error when a WDL file only contains a task and task name is not specified

### ISSUE THREAD

**Issue by jtratner** [EliLillyCo/pytest-wdl#87]
See this zip file for example - [no-workflow-name-bad-error.zip](https://github.com/EliLillyCo/pytest-wdl/files/3921518/no-workflow-name-bad-error.zip)

But basically if you only have single task in a file and don't specify a workflow name, you get an error like this:

```
        if not task:
            if "workflow_name" in kwargs:
                namespace = kwargs["workflow_name"]
            else:
>               namespace = doc.workflow.name
E               AttributeError: 'NoneType' object has no attribute 'name'

../../.pyenv/versions/3.6.4/lib/python3.6/site-packages/pytest_wdl/executors/miniwdl.py:72: AttributeError
```

Might be nice to have slightly better error message in this case

**Comment by jdidion** [comment]
Hi Jeff - this definitely needs to be documented better, but you can add a `task_name=mytask` keyword argument to the call to workflow_runner, e.g.

```
workflow_runner(
  wdl_script=str(p),
  inputs=inputs,
  task_name=mytask
)
```

**Comment by jdidion** [comment]
Also note - cromwell doesn't allow running a task-only wdl file, so you'll need to configure it to only use miniwdl. This can be done in a few ways, depending on if you want to configure just this test, or to have all your tests only use miniwdl. In the former case, you can add `executors=['miniwdl']` keyword argument to the workflow_runner call. In the latter case, you can add `"executors": ["miniwdl"]` to the config file.

**Comment by jdidion** [comment]
It also looks like we need to add a way to configure the search paths for locating WDL files. I'll open a separate issue for that.

**Comment by jdidion** [comment]
1.2.0 is now released. This should be fixed.
